name       : python-plum
version    : 0.7.9
release    : 5
source     :
    - https://pypi.io/packages/source/p/plum-py/plum-py-0.7.9.tar.gz : 4499f4fd3148aff52c9519f5a33f979b95fefe0ee3b2c275b13716944e45a802
homepage   : https://gitlab.com/dangass/plum
license    : MIT
component  : programming.python
summary    : Pack/Unpack Memory in Python
description: |
    The plum-py Python package provides classes and utility functions to transform byte sequences into Python objects and back. While similar in purpose to Python’s standard library struct module, this package provides a larger set of format specifiers and is extensible, allowing you to easily create complex ones of your own.
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # Need to package python-baseline
#    %python3_test pytest3 -v
