name       : python-plum
version    : 0.8.5
release    : 6
source     :
    - https://pypi.io/packages/source/p/plum-py/plum-py-0.8.5.tar.gz : 5bb0e20d7f51337f716dab073018c6f183e3a965e33979e1d3b98634e967b5d8
homepage   : https://gitlab.com/dangass/plum
license    : MIT
component  : programming.python
summary    : Pack/Unpack Memory in Python
description: |
    The plum-py Python package provides classes and utility functions to transform byte sequences into Python objects and back. While similar in purpose to Python’s standard library struct module, this package provides a larger set of format specifiers and is extensible, allowing you to easily create complex ones of your own.
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # Need to package python-baseline
#    %python3_test pytest3 -v
